@echo off
echo .>> canvas01.png
echo .>> canvas02.png
echo .>> canvas03.png
echo .>> canvas04.png
echo .>> canvas05.png
echo .>> canvas06.png
echo .>> canvas07.png
echo .>> canvas08.png
echo .>> canvas09.png
echo .>> canvas10.png
echo .>> canvas11.png
echo .>> canvas12.png
echo .>> canvas13.png
echo .>> canvas14.png
echo .>> canvas15.png
echo .>> canvas16.png
echo .>> canvas17.png
echo .>> canvas18.png
echo .>> canvas19.png
echo .>> canvas20.png
echo .>> canvas21.png
echo .>> canvas22.png
echo .>> canvas23.png
echo .>> canvas24.png
echo .>> canvas25.png
echo .>> canvas26.png
echo .>> canvas27.png
echo .>> canvas28.png
echo .>> canvas29.png
echo .>> canvas30.png
echo .>> canvas31.png
echo .>> canvas32.png
echo .>> canvas33.png
echo .>> canvas34.png
echo .>> canvas35.png
echo .>> canvas36.png
echo .>> canvas37.png
echo .>> canvas38.png
echo .>> canvas39.png
echo .>> canvas40.png
echo .>> canvas41.png
echo .>> canvas42.png
echo .>> canvas43.png
echo .>> canvas44.png
echo .>> canvas45.png
echo .>> canvas46.png
echo .>> canvas47.png
echo .>> canvas48.png
echo .>> canvas49.png
echo .>> canvas50.png
echo .>> canvas51.png
echo .>> canvas52.png
echo .>> canvas53.png
echo .>> canvas54.png
echo .>> canvas55.png
echo .>> canvas56.png
echo .>> canvas57.png
echo .>> canvas58.png
echo .>> canvas59.png
echo .>> canvas60.png
pause
